#!/bin/bash

# writes screenshots of wallpaperengine content to a directory

if [ "$#" -eq 1 ];
then
    for mv in ~/.local/share/Steam/steamapps/workshop/content/431960/*/; do
        dir=${mv%*/}
        filename="$1${dir##*/}.png"
        echo "$filename"
        if [[ ! -f "$filename" ]]; then
        linux-wallpaperengine --screenshot "$filename" "${dir##*/}" &
        sleep 2
        killall linux-wallpaperengine
        fi
    done
fi